using System;
using System.Globalization;
using System.Linq;
using ChartForgeX;
using ChartForgeX.Core;
using ChartForgeX.Html;
using ChartForgeX.Primitives;
using ChartForgeX.Rendering;
using ChartForgeX.Themes;

namespace ChartForgeX.Tests;

internal static partial class SmokeTests {
    private static void PublicApiRejectsInvalidInputs() {
        AssertThrows<ArgumentNullException>(() => Chart.Create().WithTitle(null!), "Chart titles should reject null values.");
        AssertThrows<ArgumentNullException>(() => Chart.Create().Title = null!, "Chart title property should reject null values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithSize(0, 360), "Chart sizes should reject non-positive dimensions.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithPadding(1, double.NaN, 1, 1), "Chart padding should reject non-finite values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithTickCount(1), "Tick counts should reject values below two.");
        AssertThrows<ArgumentNullException>(() => Chart.Create().Options.Theme = null!, "Chart options should reject null themes.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().Options.TickCount = 1, "Chart options should reject invalid tick counts.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().Options.XAxisLabelDensity = (ChartLabelDensity)999, "Chart options should reject unknown label density values.");
        AssertThrows<ArgumentException>(() => Chart.Create().WithPngFont(" "), "PNG font paths should reject empty values.");
        AssertThrows<ArgumentException>(() => Chart.Create().WithPngFont("font.ttc", faceName: " "), "PNG font face names should reject empty values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithPngFont("font.ttc", -1), "PNG font collection indexes should reject negative values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartSize(-1, 100), "ChartSize should reject non-positive dimensions.");
        AssertThrows<ArgumentOutOfRangeException>(() => ChartPadding.All(double.NegativeInfinity), "ChartPadding should reject non-finite values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartPoint(1, double.NaN), "ChartPoint should reject non-finite values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartRect(0, 0, -1, 10), "ChartRect should reject negative dimensions.");
        AssertThrows<ArgumentNullException>(() => new ChartAxisLabel(1, null!), "Axis labels should reject null text.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartAxisLabel(double.NaN, "bad"), "Axis labels should reject non-finite values.");
        AssertThrows<ArgumentException>(() => Chart.Create().WithXLabels(new[] { default(ChartAxisLabel) }), "Explicit axis labels should reject default labels with null text.");
        AssertThrows<ArgumentNullException>(() => ChartTheme.Light().Palette = null!, "Themes should reject null palettes.");
        AssertThrows<ArgumentException>(() => ChartTheme.Light().Palette = Array.Empty<ChartColor>(), "Themes should reject empty palettes.");
        AssertThrows<ArgumentException>(() => ChartColor.FromHex("#12"), "Hex colors should reject invalid lengths.");
        AssertThrows<ArgumentException>(() => ChartColor.FromHex("#ggg"), "Hex colors should reject invalid characters.");
        AssertThrows<ArgumentException>(() => ChartPalettes.FromHex(), "Hex palette helpers should reject empty palettes.");
        AssertThrows<ArgumentOutOfRangeException>(() => ChartTheme.Light().TitleFontSize = 0, "Themes should reject non-positive font sizes.");
        AssertThrows<ArgumentOutOfRangeException>(() => ChartTheme.Light().ShadowOpacity = 2, "Themes should reject opacity values outside zero to one.");
        AssertThrows<ArgumentOutOfRangeException>(() => ChartTheme.Light().WithSurfaceStyle((ChartSurfaceStyle)999), "Themes should reject unknown surface styles.");
        AssertThrows<ArgumentNullException>(() => ChartTheme.Light().FontFamily = null!, "Themes should reject null font families.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddLine("Values", new[] { new ChartPoint(1, double.PositiveInfinity) }), "Series should reject non-finite point values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartSeries("Values", (ChartSeriesKind)999, Points(1, 2, 3)), "Series should reject unknown series kinds.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddLine("Values", Points(1, 2, 3)).Series[0].StrokeWidth = 0, "Series stroke widths should reject non-positive values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddLine("Values", Points(1, 2, 3)).Series[0].StrokeWidth = double.NaN, "Series stroke widths should reject non-finite values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddLine("Values", Points(1, 2, 3)).Series[0].YAxis = (ChartAxisSide)99, "Series y-axis side should reject unknown enum values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartAnnotation((ChartAnnotationKind)999, 1, null, "bad", ChartColor.Black, 1), "Annotations should reject unknown annotation kinds.");
        AssertThrows<ArgumentException>(() => new ChartAnnotation(ChartAnnotationKind.HorizontalBand, 1, null, "bad", ChartColor.Black, 0.2), "Band annotations should require an end value.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartAnnotation(ChartAnnotationKind.VerticalBand, 1, 1, "bad", ChartColor.Black, 0.2), "Band annotations should reject empty ranges.");
        AssertThrows<ArgumentException>(() => new ChartAnnotation(ChartAnnotationKind.HorizontalLine, 1, 2, "bad", ChartColor.Black, 1), "Line annotations should reject unused end values.");
        AssertThrows<ArgumentNullException>(() => Chart.Create().WithSecondaryYAxis(null!), "Secondary y-axis titles should reject null.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithSecondaryYAxisBounds(10, 10), "Secondary y-axis bounds should reject empty numeric domains.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddHistogram("Empty", Array.Empty<double>()), "Histograms should reject empty raw value sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddHistogram("Bad", new[] { 1d, 2d }, 0), "Histograms should reject bin counts below one.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddHistogram("Bad", new[] { 1d, double.NaN }), "Histograms should reject non-finite raw values.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddTrendLine("Empty", Array.Empty<ChartPoint>()), "Trend lines should reject empty source points.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddTrendLine("Vertical", new[] { new ChartPoint(1, 2), new ChartPoint(1, 4) }), "Trend lines should reject source points with no x variation.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddCircle("Bad", 50, 100, 100), "Circle charts should reject empty numeric domains.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddCircle("Bad", double.NaN), "Circle charts should reject non-finite values.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddRangeBar("Empty", Array.Empty<ChartInterval>()), "Range bars should reject empty interval sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartInterval(1, 2, double.NaN), "Chart intervals should reject non-finite values.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddBubble("Empty", Array.Empty<ChartBubble>()), "Bubble charts should reject empty value sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartBubble(1, 2, 0), "Bubble charts should reject non-positive sizes.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartBubble(1, 2, double.NaN), "Bubble charts should reject non-finite sizes.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddErrorBar("Empty", Array.Empty<ChartErrorBar>()), "Error bars should reject empty value sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartErrorBar(1, 5, 6, 8), "Error bars should reject lower bounds above the point estimate.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartErrorBar(1, 5, 2, 4), "Error bars should reject upper bounds below the point estimate.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartErrorBar(1, 5, 2, double.NaN), "Error bars should reject non-finite bounds.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddCandlestick("Empty", Array.Empty<ChartCandlestick>()), "Candlestick charts should reject empty value sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartCandlestick(1, 5, 4, 2, 3), "Candlestick charts should reject high values below open or close values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartCandlestick(1, 5, 8, 6, 7), "Candlestick charts should reject low values above open or close values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartCandlestick(1, 5, 8, double.NaN, 7), "Candlestick charts should reject non-finite OHLC values.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddRangeBand("Empty", Array.Empty<ChartRangeBand>()), "Range bands should reject empty value sets.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddRangeArea("Empty", Array.Empty<ChartRangeBand>()), "Range areas should reject empty value sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartRangeBand(1, 8, 4), "Range bands should reject lower values above upper values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartRangeBand(1, double.NaN, 4), "Range bands should reject non-finite values.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddDumbbell("Empty", Array.Empty<ChartDumbbell>()), "Dumbbell charts should reject empty value sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartDumbbell(1, double.NaN, 4), "Dumbbell charts should reject non-finite values.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddHeatmapRow("Empty", Array.Empty<ChartPoint>()), "Heatmap rows should reject empty value sets.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddPareto("Empty", Array.Empty<ChartParetoItem>()), "Pareto charts should reject empty item sets.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddPareto("Zero", new[] { new ChartParetoItem("A", 0), new ChartParetoItem("B", 0) }), "Pareto charts should reject all-zero item sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartParetoItem("Bad", -1), "Pareto items should reject negative values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartParetoItem("Bad", double.NaN), "Pareto items should reject non-finite values.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddTreemap("Empty", Array.Empty<ChartTreemapItem>()), "Treemaps should reject empty item sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartTreemapItem("Bad", "Bad", value: -1), "Treemap items should reject negative values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartTreemapItem("Bad", "Bad", value: double.NaN), "Treemap items should reject non-finite values.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddPictorial("Empty", Array.Empty<ChartPictorialItem>()), "Pictorial charts should reject empty item sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartPictorialItem("Bad", -1), "Pictorial items should reject negative values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartPictorialItem("Bad", double.NaN), "Pictorial items should reject non-finite values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddPictorial("Bad", new[] { new ChartPictorialItem("A", 1) }, (ChartPictorialShape)999), "Pictorial charts should reject unknown shapes.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithPictorialShape((ChartPictorialShape)999), "Pictorial shape customization should reject unknown shapes.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithPictorialColumns(0), "Pictorial charts should reject column counts below one.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().Options.PictorialColumns = 101, "Pictorial chart options should reject excessive column counts.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithPictorialMaximum(0), "Pictorial charts should reject zero scale maximums.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().Options.PictorialMaximum = double.NaN, "Pictorial chart options should reject non-finite scale maximums.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithPictorialValuePerSymbol(0), "Pictorial charts should reject zero value-per-symbol scales.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().Options.PictorialValuePerSymbol = double.NaN, "Pictorial chart options should reject non-finite value-per-symbol scales.");
        AssertThrows<ArgumentException>(() => Chart.Create().WithPictorialSvgPath(""), "Pictorial charts should reject empty SVG path data.");
        AssertThrows<ArgumentException>(() => Chart.Create().WithPictorialSvgPath("M0 0 <script>"), "Pictorial charts should reject unsafe SVG path data.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithPictorialSvgPath("M0 0 L1 1 Z", new ChartRect(0, 0, 0, 24)), "Pictorial charts should reject empty SVG path viewBoxes.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithPictorialSvgPath("M0 0 L1 1 Z", (ChartPictorialShape)999), "Pictorial charts should reject unknown PNG fallback shapes.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddWordCloud("Empty", Array.Empty<ChartWordCloudItem>()), "Word clouds should reject empty item sets.");
        AssertThrows<ArgumentException>(() => new ChartWordCloudItem("", 1), "Word cloud terms should reject empty text.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartWordCloudItem("Bad", -1), "Word cloud terms should reject negative weights.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartWordCloudItem("Bad", double.NaN), "Word cloud terms should reject non-finite weights.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithWordCloudFontRange(0, 40), "Word clouds should reject non-positive minimum font sizes.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithWordCloudFontRange(40, 40), "Word clouds should reject inverted font ranges.");
        AssertThrows<ArgumentException>(() => Chart.Create().WithWordCloudAngles(), "Word clouds should reject empty angle patterns.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithWordCloudAngles(-91), "Word clouds should reject excessive term rotation.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithWordCloudMaximumTerms(0), "Word clouds should reject non-positive term limits.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithWordCloudDensity(0.49), "Word clouds should reject overly loose layout density.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithWordCloudDensity(2.01), "Word clouds should reject overly dense layout density.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddBoxPlot("Empty", Array.Empty<ChartBoxPlot>()), "Box plots should reject empty summary sets.");
        AssertThrows<ArgumentNullException>(() => Chart.Create().AddBoxPlot("Raw", 1, null!), "Raw box plots should reject null sample sets.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddBoxPlot("Raw", 1, Array.Empty<double>()), "Raw box plots should reject empty sample sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddBoxPlot("Raw", double.PositiveInfinity, new[] { 1d, 2d }), "Raw box plots should reject non-finite x values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddBoxPlot("Raw", 1, new[] { 1d, double.NaN }), "Raw box plots should reject non-finite sample values.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartBoxPlot(1, 5, 4, 3, 2, 1), "Box plots should reject unordered summary values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddGauge("Score", 80, 100, 0), "Gauges should reject inverted scales.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddProgressRing("Empty", Array.Empty<ChartPoint>()), "Progress rings should reject empty value sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddProgressRing("Bad", Points(101)), "Progress rings should reject values above 100.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddProgressRing("Bad", Points(-1)), "Progress rings should reject negative values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddTimelineRange("Task", 10, 2), "Timelines should reject inverted ranges.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddGanttTask("Task", 10, 2), "Gantt tasks should reject inverted ranges.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddGanttTask("Task", 1, 2, 1.1), "Gantt tasks should reject progress above one.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddGanttTask("Task", 1, 2, dependsOn: 0), "Gantt tasks should reject dependencies that do not reference earlier tasks.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithGanttToday(double.NaN), "Gantt today markers should reject non-finite values.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddSankey("Flow", new[] { new ChartNode("A", "A"), new ChartNode("B", "B") }, Array.Empty<ChartFlowLink>()), "Sankey charts should reject empty link sets.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddSankey("Flow", new[] { new ChartNode("A", "A"), new ChartNode("B", "B") },
            new[] { new ChartFlowLink("flow-1", "A", "B", 0) }), "Sankey charts should reject non-positive flow values before adding a series.");
        AssertThrows<ArgumentException>(() => new ChartFlowLink("flow-2", "", "B", 1), "Sankey links should reject empty source labels.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddSankey("Flow", new[] { new ChartNode("A", "A") }, new[] { new ChartFlowLink("flow-3", "A", "A", 1) }), "Sankey charts should reject self links.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddSankey("Flow", new[] { new ChartNode("A", "A"), new ChartNode("B", "B") }, new[] { new ChartFlowLink("flow-4", "A", "B", 1), new ChartFlowLink("flow-5", "B", "A", 1) }), "Sankey charts should reject cyclic link sets.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddTree("Tree", new[] { new ChartNode("A", "A"), new ChartNode("B", "B") }, Array.Empty<ChartTreeLink>()), "Tree charts should reject empty link sets.");
        AssertThrows<ArgumentOutOfRangeException>(() => new ChartTreeLink("A", "B", 0), "Tree links should reject non-positive values.");
        AssertThrows<ArgumentException>(() => new ChartTreeLink("", "B"), "Tree links should reject empty parent labels.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddTree("Tree", new[] { new ChartNode("A", "A") }, new[] { new ChartTreeLink("A", "A") }), "Tree charts should reject self links.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddTree("Tree", new[] { new ChartNode("A", "A"), new ChartNode("C", "C"), new ChartNode("B", "B") }, new[] { new ChartTreeLink("A", "C"), new ChartTreeLink("B", "C") }), "Tree charts should reject multiple parents for a child.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddTree("Tree", new[] { new ChartNode("A", "A"), new ChartNode("B", "B"), new ChartNode("C", "C"), new ChartNode("D", "D") }, new[] { new ChartTreeLink("A", "B"), new ChartTreeLink("C", "D") }), "Tree charts should reject multiple roots.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddSunburst("Sunburst", new[] { new ChartNode("A", "A"), new ChartNode("B", "B") }, Array.Empty<ChartTreeLink>()), "Sunburst charts should reject empty link sets.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddSunburst("Sunburst", new[] { new ChartNode("A", "A") }, new[] { new ChartTreeLink("A", "A") }), "Sunburst charts should reject self links.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddSunburst("Sunburst", new[] { new ChartNode("A", "A"), new ChartNode("C", "C"), new ChartNode("B", "B") }, new[] { new ChartTreeLink("A", "C"), new ChartTreeLink("B", "C") }), "Sunburst charts should reject multiple parents for a child.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddSunburst("Sunburst", new[] { new ChartNode("A", "A"), new ChartNode("B", "B"), new ChartNode("C", "C"), new ChartNode("D", "D") }, new[] { new ChartTreeLink("A", "B"), new ChartTreeLink("C", "D") }), "Sunburst charts should reject multiple roots.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddHorizontalBand(1, 2, opacity: 1.5), "Band opacity should reject values outside zero to one.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddMeanLine("Mean", Array.Empty<ChartPoint>()), "Mean overlays should reject empty source points.");
        AssertThrows<ArgumentException>(() => Chart.Create().AddStandardDeviationBand("Sigma", Points(10)), "Standard deviation bands should reject single-point source data.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().AddStandardDeviationBand("Sigma", Points(10, 20), 0), "Standard deviation bands should reject non-positive deviation counts.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithXAxisBounds(10, 10), "X-axis bounds should reject empty ranges.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithXAxisBounds(double.NaN, 10), "X-axis bounds should reject non-finite minimum values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().Options.XAxisMaximum = double.PositiveInfinity, "X-axis option bounds should reject non-finite maximum values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithYAxisBounds(10, 10), "Y-axis bounds should reject empty ranges.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().WithYAxisBounds(double.NaN, 10), "Y-axis bounds should reject non-finite minimum values.");
        AssertThrows<ArgumentOutOfRangeException>(() => Chart.Create().Options.YAxisMaximum = double.PositiveInfinity, "Y-axis option bounds should reject non-finite maximum values.");
        AssertThrows<ArgumentNullException>(() => ChartGrid.Create().WithTitle(null!), "Chart grids should reject null titles.");
        AssertThrows<ArgumentNullException>(() => ChartGrid.Create().Add(null!), "Chart grids should reject null charts.");
        AssertThrows<ArgumentOutOfRangeException>(() => ChartGrid.Create().WithColumns(0), "Chart grids should reject non-positive column counts.");
        AssertThrows<ArgumentOutOfRangeException>(() => ChartGrid.Create().WithGap(-1), "Chart grids should reject negative gaps.");
        AssertThrows<ArgumentOutOfRangeException>(() => ChartGrid.Create().WithPadding(-1), "Chart grids should reject negative padding.");
        AssertThrows<ArgumentOutOfRangeException>(() => ChartGrid.Create().WithPanelSize(0, 200), "Chart grids should reject non-positive panel widths.");
        AssertThrows<ArgumentOutOfRangeException>(() => ChartGrid.Create().PanelSize = default(ChartSize), "Chart grid panel size setters should reject non-positive dimensions.");
        AssertThrows<ArgumentOutOfRangeException>(() => ChartGrid.Create().WithPanelFit((VisualPanelFit)999), "Chart grids should reject unknown panel fit values.");
        AssertThrows<ArgumentNullException>(() => ChartGrid.Create().WithTheme(null!), "Chart grids should reject null themes.");
        AssertThrows<InvalidOperationException>(() => ChartGrid.Create().WithSharedXAxis(), "Shared x-axis grids should reject empty grids.");
        AssertThrows<InvalidOperationException>(() => ChartGrid.Create().Add(Chart.Create().AddGauge("Score", 87)).WithSharedXAxis(), "Shared x-axis grids should require cartesian charts.");
        AssertThrows<InvalidOperationException>(() => ChartGrid.Create().WithSharedAxes(), "Shared-axis grids should reject empty grids.");
        AssertThrows<InvalidOperationException>(() => ChartGrid.Create().WithSharedYAxis(), "Shared y-axis grids should reject empty grids.");
        AssertThrows<InvalidOperationException>(() => ChartGrid.Create().Add(Chart.Create().AddGauge("Score", 87)).WithSharedYAxis(), "Shared y-axis grids should require cartesian charts.");
        AssertThrows<ArgumentNullException>(() => ChartExtensions.ToSvg((ChartGrid)null!), "Chart grid SVG export should reject null grids.");
        AssertThrows<ArgumentNullException>(() => ChartExtensions.ToPng((ChartGrid)null!), "Chart grid PNG export should reject null grids.");
        AssertThrows<ArgumentNullException>(() => ChartExtensions.GetPngFontInfo(null!), "PNG font diagnostics should reject null charts.");
        AssertThrows<ArgumentNullException>(() => new HtmlChartRenderer().RenderFragment(null!), "HTML fragment rendering should reject null charts.");
        AssertThrows<ArgumentNullException>(() => new HtmlChartRenderer().RenderPage(null!), "HTML page rendering should reject null charts.");
        AssertThrows<ArgumentNullException>(() => new HtmlChartGridRenderer().RenderPage(null!), "HTML grid rendering should reject null grids.");
        AssertThrows<InvalidOperationException>(() => ChartGrid.Create().ToHtmlPage(), "HTML grid rendering should reject empty grids.");
        var chartWithNullSeries = Chart.Create();
        chartWithNullSeries.Series.Add(null!);
        AssertThrows<InvalidOperationException>(() => chartWithNullSeries.ToSvg(), "Rendering should reject null entries in the public series collection.");
        var chartWithNullAnnotation = Chart.Create().AddLine("Values", Points(1, 2, 3));
        chartWithNullAnnotation.Annotations.Add(null!);
        AssertThrows<InvalidOperationException>(() => chartWithNullAnnotation.ToPng(), "Rendering should reject null entries in the public annotation collection.");
        var chartWithDefaultAxisLabel = Chart.Create().AddLine("Values", Points(1, 2, 3));
        chartWithDefaultAxisLabel.Options.XAxisLabels.Add(default);
        AssertThrows<InvalidOperationException>(() => chartWithDefaultAxisLabel.ToSvg(), "Rendering should reject default axis labels added through the mutable options collection.");
        var malformedBubble = Chart.Create();
        malformedBubble.Series.Add(new ChartSeries("Bad", ChartSeriesKind.Bubble, new[] { new ChartPoint(1, 2) }));
        AssertThrows<InvalidOperationException>(() => malformedBubble.ToSvg(), "Bubble renderers should reject incomplete public series tuples.");
        var malformedErrorBar = Chart.Create();
        malformedErrorBar.Series.Add(new ChartSeries("Bad", ChartSeriesKind.ErrorBar, new[] { new ChartPoint(1, 5), new ChartPoint(1, 6), new ChartPoint(1, 8) }));
        AssertThrows<InvalidOperationException>(() => malformedErrorBar.ToPng(), "Error-bar renderers should reject inverted public lower bounds.");
        var malformedCandlestick = Chart.Create();
        malformedCandlestick.Series.Add(new ChartSeries("Bad", ChartSeriesKind.Candlestick, new[] { new ChartPoint(1, 5), new ChartPoint(1, 4), new ChartPoint(1, 2), new ChartPoint(1, 3) }));
        AssertThrows<InvalidOperationException>(() => malformedCandlestick.ToSvg(), "Candlestick renderers should reject malformed public OHLC tuples.");
        var malformedBoxPlot = Chart.Create();
        malformedBoxPlot.Series.Add(new ChartSeries("Bad", ChartSeriesKind.BoxPlot, new[] { new ChartPoint(1, 1), new ChartPoint(1, 4), new ChartPoint(1, 3), new ChartPoint(1, 5), new ChartPoint(1, 6) }));
        AssertThrows<InvalidOperationException>(() => malformedBoxPlot.ToPng(), "Box plot renderers should reject unordered public summary tuples.");
        var fractionalGanttDependency = Chart.Create();
        fractionalGanttDependency.Series.Add(new ChartSeries("A", ChartSeriesKind.Gantt, new[] { new ChartPoint(1, 2), new ChartPoint(1, -1), new ChartPoint(0, 0) }));
        fractionalGanttDependency.Series.Add(new ChartSeries("B", ChartSeriesKind.Gantt, new[] { new ChartPoint(2, 3), new ChartPoint(1, 0.4), new ChartPoint(0, 0) }));
        AssertThrows<InvalidOperationException>(() => fractionalGanttDependency.ToSvg(), "Gantt renderers should reject fractional dependency indexes instead of rounding them.");
    }

    private static void SpecializedChartsRejectMixedSeries() {
        AssertThrows<InvalidOperationException>(() => Chart.Create().AddGauge("Score", 87).AddLine("Trend", Points(1, 2, 3)).ToSvg(), "SVG rendering should reject mixed specialized and cartesian series.");
        AssertThrows<InvalidOperationException>(() => Chart.Create().AddDonut("Checks", Points(70, 20)).AddPie("Other", Points(1, 2)).ToPng(), "PNG rendering should reject multiple pie-like series.");
        AssertThrows<InvalidOperationException>(() => Chart.Create().AddGauge("Score", 87).AddGauge("Other", 72).ToSvg(), "Single-panel specialized charts should reject multiple series.");
        AssertThrows<InvalidOperationException>(() => Chart.Create().AddDonut("Empty", Points(-3, 0, -2)).ToPng(), "Donut charts should reject data with no positive slice values.");
        AssertThrows<InvalidOperationException>(() => Chart.Create().AddPie("Bad", Points(20, -1, 30)).ToSvg(), "Pie charts should reject negative slice values instead of silently filtering them.");
        AssertThrows<InvalidOperationException>(() => Chart.Create().AddFunnel("Empty", Points(0, -1, 0)).ToSvg(), "Funnel charts should reject data with no positive stage values.");
        AssertThrows<InvalidOperationException>(() => Chart.Create().AddFunnel("Bad", Points(100, -10, 50)).ToSvg(), "Funnel charts should reject negative stage values instead of silently filtering them.");
        AssertThrows<InvalidOperationException>(() => Chart.Create().AddPolarArea("Empty", Points(0, -1, 0)).ToSvg(), "Polar-area charts should reject data with no positive segment values.");
        AssertThrows<InvalidOperationException>(() => Chart.Create().AddPolarArea("Bad", Points(30, -1, 40)).ToPng(), "Polar-area charts should reject negative segment values instead of silently filtering them.");
        AssertThrows<InvalidOperationException>(() => Chart.Create().AddRadar("Too small", Points(72, 84)).ToPng(), "Radar charts should reject fewer than three categories instead of rendering a blank chart.");
        var malformedHeatmap = Chart.Create();
        malformedHeatmap.Series.Add(new ChartSeries("Bad", ChartSeriesKind.Heatmap, Array.Empty<ChartPoint>()));
        Assert(malformedHeatmap.ToSvg().Contains("matrix-no-data"), "Empty heatmap rows should render the native no-data scene.");
        var malformedBullet = Chart.Create();
        malformedBullet.Series.Add(new ChartSeries("Bad", ChartSeriesKind.Bullet, Points(72)));
        AssertThrows<InvalidOperationException>(() => malformedBullet.ToSvg(), "Bullet renderers should reject malformed public series instead of rendering a blank chart.");
        var malformedGantt = Chart.Create();
        malformedGantt.Series.Add(new ChartSeries("Bad", ChartSeriesKind.Gantt, Points(1, 2)));
        AssertThrows<InvalidOperationException>(() => malformedGantt.ToPng(), "Gantt renderers should reject malformed public series instead of rendering a blank chart.");
        foreach (var kind in new[] { ChartSeriesKind.Sankey, ChartSeriesKind.Tree, ChartSeriesKind.Sunburst, ChartSeriesKind.Treemap }) {
            AssertThrows<ArgumentException>(() => new ChartSeries("Raw", kind, Points(1)), "Relationship constructors require typed nodes, links, or items.");
            var incompatible = Chart.Create();
            var raw = new ChartSeries("Raw", kind, Array.Empty<ChartPoint>());
            incompatible.Series.Add(raw);
            var prepared = incompatible.Prepare(new VisualRenderContext());
            var diagnostic = kind == ChartSeriesKind.Sankey ? "sankey.no-data" : "hierarchy.no-data";
            Assert(prepared.Diagnostics.Any(item => item.Code == diagnostic), "An empty relationship series retains its native no-data diagnostic.");
            Assert(!prepared.Scene.Nodes.OfType<VisualSceneGroup>().Any(group =>
                group.Metadata.TryGetValue("data-cfx-target-kind", out var targetKind) && (targetKind == "node" || targetKind == "link")),
                "An empty relationship series does not invent interactive node or link targets.");
            Assert(!string.IsNullOrWhiteSpace(prepared.ToSvg()), "An empty relationship series still exports its native frame.");
            raw.Points.Add(new ChartPoint(0, 1));
            AssertThrows<InvalidOperationException>(() => incompatible.ToSvg(), "Relationship SVG exports reject added raw points.");
            AssertThrows<InvalidOperationException>(() => incompatible.ToPng(), "Relationship PNG exports reject added raw points.");
        }
    }
}
