using System;
using ChartForgeX.Interactivity;
using ChartForgeX.Interactivity.Html;

namespace ChartForgeX.Tests;

internal static partial class SmokeTests {
    private static void GraphExplorerAccessibilityAndFrameTelemetryStayHonest() {
        var scene = SampleGraphScene();
        scene.Options.Enable(GraphSceneFeatures.Export);
        var html = new HtmlGraphExplorerRenderer().RenderPage(scene);
        Assert(html.Contains("class=\"cfx-graph-canvas\" data-cfx-role=\"graph-canvas\" width=\"960\" height=\"560\" role=\"img\" aria-hidden=\"true\"", StringComparison.Ordinal) && html.Contains("Interactive graph. Use arrow keys to move between nodes", StringComparison.Ordinal), "Graph explorer pages should initially hide the inactive Canvas target and retain useful keyboard instructions for when it becomes active.");
        Assert(html.Contains("class=\"cfx-graph-webgl\" data-cfx-role=\"graph-webgl\" width=\"960\" height=\"560\" role=\"img\" aria-hidden=\"true\"", StringComparison.Ordinal), "Graph explorer pages should initially hide the inactive WebGL rendering target from assistive technology.");
        Assert(html.Contains("data-cfx-role=\"graph-scene\" width=\"960\" height=\"560\" viewBox=\"0 0 960 560\" role=\"group\" aria-hidden=\"false\"", StringComparison.Ordinal), "Selectable SVG graphs should expose an interactive group instead of flattening all graph items into a single image role.");
        Assert(html.Contains("syncRendererAccessibility(root, renderer)", StringComparison.Ordinal) && html.Contains("canvas.setAttribute('aria-hidden', renderer === 'canvas' ? 'false' : 'true')", StringComparison.Ordinal) && html.Contains("webgl.setAttribute('aria-hidden', renderer === 'webgl' ? 'false' : 'true')", StringComparison.Ordinal) && html.Contains("svg.setAttribute('aria-hidden', renderer === 'svg' ? 'false' : 'true')", StringComparison.Ordinal), "Graph explorer runtime should expose exactly one accessible rendering surface after SVG, Canvas, or WebGL backend decisions.");
        Assert(html.Contains("data-cfx-graph-theme=\"system\"", StringComparison.Ordinal) && html.Contains("data-cfx-graph-theme-persist=\"true\"", StringComparison.Ordinal) && html.Contains("data-cfx-graph-action=\"theme\"", StringComparison.Ordinal), "Graph explorer pages should default to a persistent system-aware appearance control.");
        Assert(html.Contains("role=\"group\" aria-label=\"Find and filter\"", StringComparison.Ordinal) && html.Contains("aria-label=\"Filter by status\"", StringComparison.Ordinal) && html.Contains("role=\"toolbar\" aria-label=\"Graph commands\"", StringComparison.Ordinal), "Graph explorer search, filters, and floating command rail should expose explicit accessible names.");
        Assert(html.Contains("class=\"cfx-graph-command-menu\"", StringComparison.Ordinal) && html.Contains("role=\"button\" aria-label=\"Export graph\" aria-expanded=\"false\"", StringComparison.Ordinal) && html.Contains("data-cfx-tooltip=\"Export graph\"", StringComparison.Ordinal) && html.Contains("data-cfx-tooltip=\"Fit graph to view\"", StringComparison.Ordinal), "Graph explorer commands should replace cryptic title-only glyphs with an expanded-state export control and accessible custom tooltips.");
        Assert(html.Contains("data-cfx-role=\"graph-announcer\" aria-live=\"polite\" aria-atomic=\"true\"", StringComparison.Ordinal) && html.Contains("aria-keyshortcuts', 'ArrowUp ArrowDown ArrowLeft ArrowRight Home End Enter Space'", StringComparison.Ordinal), "Graph explorer pages should announce state changes and expose a bounded roving keyboard model for large SVG topologies.");
        Assert(html.Contains("data-cfx-role=\"graph-node\" role=\"button\" aria-pressed=\"false\"", StringComparison.Ordinal) && html.Contains("item.setAttribute('aria-pressed', item.classList.contains('cfx-graph-selected') ? 'true' : 'false')", StringComparison.Ordinal), "Selectable SVG items should expose recognizable button semantics and synchronize pressed state with visual selection.");
        var style = HtmlGraphExplorerRenderer.BuildFragmentStyle();
        Assert(style.Contains("--cfx-control-height: 42px", StringComparison.Ordinal) && style.Contains("outline: 3px solid var(--cfx-color-focus)", StringComparison.Ordinal), "Graph explorer controls should provide comfortable targets and a high-visibility focus indicator in every theme.");
        Assert(style.Contains(".cfx-graph-command-rail", StringComparison.Ordinal) && style.Contains("appearance: none", StringComparison.Ordinal) && style.Contains("content: attr(data-cfx-tooltip)", StringComparison.Ordinal), "Graph explorer chrome should use a floating command rail, custom filter indicators, and one consistent tooltip system instead of native arrows and browser-title hints.");
        Assert(style.Contains("@media (prefers-reduced-motion: reduce)", StringComparison.Ordinal) && style.Contains("@media (forced-colors: active)", StringComparison.Ordinal) && style.Contains("@media (prefers-contrast: more)", StringComparison.Ordinal), "Graph explorer CSS should honor reduced motion, forced colors, and increased contrast preferences.");
        var runtime = HtmlGraphExplorerRenderer.BuildInteractionScript();
        Assert(runtime.Contains("const graphThemePalette", StringComparison.Ordinal) && runtime.Contains("cfxgraphthemechange", StringComparison.Ordinal) && runtime.Contains("theme: (target, mode)", StringComparison.Ordinal), "Graph explorer runtime should expose one reusable theme palette, host API, and change event across renderers.");
        Assert(runtime.Contains(".cfx-graph-command-rail,.cfx-graph-breadcrumbs", StringComparison.Ordinal) && runtime.Contains("bindCommandMenus(root)", StringComparison.Ordinal) && runtime.Contains("event.key !== 'Escape'", StringComparison.Ordinal), "Floating graph chrome should remain operable without stage handlers swallowing it, and export menus should close outside or with Escape.");
        Assert(runtime.Contains("const physical = (selector) => Array.from(root.querySelectorAll(selector))", StringComparison.Ordinal), "Theme switching should update physical SVG elements without treating accelerated virtual graph records as DOM nodes.");
        Assert(runtime.Contains("if (!graphPrefersReducedMotion(root)) applyLayout(root, state)", StringComparison.Ordinal) && runtime.Contains("message.type === 'done' || !graphPrefersReducedMotion(root)", StringComparison.Ordinal) && runtime.Contains("graphPrefersReducedMotion(root) ? 0", StringComparison.Ordinal), "Reduced-motion mode should suppress visible intermediate physics frames and drag momentum without disabling deliberate graph movement.");
        Assert(runtime.Contains("context.fillStyle = palette.paper", StringComparison.Ordinal) && runtime.Contains("gl.clearColor(clear[0], clear[1], clear[2], 1)", StringComparison.Ordinal) && runtime.Contains("context.fillStyle = palette.paperSoft", StringComparison.Ordinal), "Canvas, WebGL, and overview surfaces should all consume the active light or dark palette.");
        Assert(runtime.Contains("graphAdaptiveTextColor", StringComparison.Ordinal) && runtime.Contains("graphColorContrast(value, graphThemePalette(root).paper) >= 4.5", StringComparison.Ordinal) && style.Contains("--cfx-node-label-explicit", StringComparison.Ordinal), "Model label colors should be retained only when they meet readable contrast against the active graph paper across SVG and Canvas.");
        Assert(style.Contains(".cfx-graph-toolbar-group--query", StringComparison.Ordinal) && style.Contains("flex-wrap: wrap", StringComparison.Ordinal) && style.Contains("color: var(--cfx-color-text)", StringComparison.Ordinal), "Narrow graph explorers should wrap named query controls without turning filters into unexplained transparent fields.");
        var darkHtml = new HtmlGraphExplorerRenderer().RenderPage(SampleGraphScene(), options => options.Theme = HtmlGraphExplorerTheme.Dark);
        Assert(darkHtml.Contains("body class=\"cfx-graph-shell cfx-graph-page-dark\"", StringComparison.Ordinal) && darkHtml.Contains("data-cfx-graph-theme=\"dark\"", StringComparison.Ordinal), "Explicit dark pages should paint the page shell and graph surface dark before browser initialization.");
        var fixedHtml = new HtmlGraphExplorerRenderer().RenderPage(SampleGraphScene(), options => {
            options.Theme = HtmlGraphExplorerTheme.Light;
            options.IncludeThemeToggle = false;
            options.PersistThemePreference = false;
        });
        Assert(fixedHtml.Contains("data-cfx-graph-theme=\"light\"", StringComparison.Ordinal) && fixedHtml.Contains("data-cfx-graph-theme-persist=\"false\"", StringComparison.Ordinal) && !fixedHtml.Contains("data-cfx-graph-action=\"theme\"", StringComparison.Ordinal), "Hosts should be able to lock a non-persistent theme and remove the appearance control.");
        AssertThrows<InvalidOperationException>(() => new HtmlGraphExplorerRenderer().RenderPage(SampleGraphScene(), options => options.Theme = (HtmlGraphExplorerTheme)999), "Graph explorer pages should reject unknown theme values instead of silently emitting an invalid contract.");
        Assert(html.Contains("detail.mode === 'frame'", StringComparison.Ordinal) && html.Contains("recordFramePerformance(root", StringComparison.Ordinal) && html.Contains("cfxGraphPerformanceMaxFrameMs", StringComparison.Ordinal), "Graph explorer runtime should measure browser frame cadence and render duration separately from physics throughput.");
        Assert(html.Contains("sampleMs: simulatedAt - started", StringComparison.Ordinal) && html.Contains("frame.renderMs, 'main'", StringComparison.Ordinal), "Main-thread graph telemetry should measure physics simulation and layout rendering separately, matching worker telemetry semantics.");
        Assert(html.Contains("physicsBudgetMisses", StringComparison.Ordinal) && html.Contains("frameSample && sampleMs > sampleBudgetMs", StringComparison.Ordinal), "Graph explorer frame-budget status should not treat multi-tick worker physics batches as animation frames.");
        Assert(html.Contains("data-cfx-performance-warmup-frames=\"4\"", StringComparison.Ordinal) && html.Contains("mode: 'warmup'", StringComparison.Ordinal) && html.Contains("const publish = steadyCount === 1", StringComparison.Ordinal) && html.Contains("cfxGraphPerformanceMaxWarmupFrameMs", StringComparison.Ordinal), "Graph explorer runtime should report configurable startup warmup cost separately and always publish the first steady-state frame without permanently failing its budget.");
        Assert(html.Contains("data-cfx-performance-worker-progress-interval=\"4\"", StringComparison.Ordinal) && html.Contains("data-cfx-performance-worker-progress-interval', 4", StringComparison.Ordinal), "Worker layout cadence should use its own performance option instead of reusing telemetry sampling cadence.");
        Assert(html.Contains("root.dataset.cfxGraphRendererActive === 'svg'", StringComparison.Ordinal) && html.Contains("const state = (root.__cfxGraphState || graphState(root))", StringComparison.Ordinal) && html.Contains("syncSvgLayout(root, state)", StringComparison.Ordinal), "Accelerated physics should avoid rewriting hidden SVG geometry while synchronizing the cached document before complete SVG export.");
        Assert(html.Contains("const moving = root.dataset.cfxGraphPhysicsState === 'running'", StringComparison.Ordinal) && html.Contains("node.shadow && !moving", StringComparison.Ordinal) && html.Contains("(!compact && !moving)", StringComparison.Ordinal), "Canvas physics should use a lightweight moving-state pass and restore labels, icons, arrows, and shadows after stabilization.");
        Assert(html.Contains("summary.budgetMissRate", StringComparison.Ordinal) && html.Contains("summary.budgetMisses >= 2 && summary.budgetMissRate > .2", StringComparison.Ordinal) && html.Contains("publish !== false", StringComparison.Ordinal), "Frame budget state should use all observed steady frames and a sustained miss rate while throttling host telemetry events.");
        var negativeWarmup = SampleGraphScene();
        negativeWarmup.Options.Performance.WarmupFrameCount = -1;
        AssertThrows<InvalidOperationException>(() => negativeWarmup.Validate(), "Graph scenes should reject negative performance warmup frame counts.");
        negativeWarmup.Options.Performance.WarmupFrameCount = 0;
        negativeWarmup.Options.Performance.WorkerProgressInterval = 0;
        AssertThrows<InvalidOperationException>(() => negativeWarmup.Validate(), "Graph scenes should reject non-positive worker progress intervals.");
    }
}
