/// <summary>
/// Writes the static example gallery page.
/// </summary>
public static class GalleryWriter {
    /// <summary>
    /// Generates an index page for all chart HTML files in the output directory.
    /// </summary>
    /// <param name="output">The directory containing generated chart files.</param>
    public static void Write(string output) {
        var htmlFiles = Directory.EnumerateFiles(output, "*.html", SearchOption.TopDirectoryOnly)
            .Where(file => !string.Equals(Path.GetFileName(file), "index.html", StringComparison.OrdinalIgnoreCase))
            .OrderBy(file => Path.GetFileName(file), StringComparer.OrdinalIgnoreCase)
            .ToArray();
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("<!doctype html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.AppendLine("<title>ChartForgeX Examples</title>");
        sb.AppendLine("<style>");
        sb.AppendLine(":root{color-scheme:dark;--bg:#0f172a;--panel:#111827;--panel2:#0b1120;--line:#253247;--text:#f8fafc;--muted:#aab6ca;--accent:#38bdf8}");
        sb.AppendLine("*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,Segoe UI,Arial,sans-serif;-webkit-font-smoothing:antialiased}");
        sb.AppendLine("header{padding:36px 40px 18px}h1{margin:0 0 8px;font-size:30px;line-height:1.1}p{margin:0;color:var(--muted);font-size:14px}");
        sb.AppendLine("main{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:22px;padding:22px 40px 44px}.card{min-width:0;border:1px solid var(--line);border-radius:8px;background:linear-gradient(180deg,var(--panel),var(--panel2));overflow:hidden}");
        sb.AppendLine(".preview{aspect-ratio:16/10;background:#0b1020;border-bottom:1px solid var(--line)}iframe{display:block;width:100%;height:100%;border:0;background:#0b1020}.body{padding:14px 16px 16px}.title{font-weight:750;font-size:15px;margin-bottom:10px}");
        sb.AppendLine(".links{display:flex;flex-wrap:wrap;gap:8px}a{color:var(--accent);text-decoration:none;font-size:12px;font-weight:700;border:1px solid rgba(56,189,248,.28);border-radius:6px;padding:6px 8px}a:hover{background:rgba(56,189,248,.12)}");
        sb.AppendLine("@media(max-width:560px){header{padding:26px 18px 12px}main{grid-template-columns:1fr;padding:18px}.preview{aspect-ratio:4/3}}");
        sb.AppendLine("</style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");
        sb.AppendLine("<header>");
        sb.AppendLine("<h1>ChartForgeX Examples</h1>");
        sb.AppendLine("<p>Static zero-dependency SVG, HTML, and PNG chart outputs generated by the example project.</p>");
        sb.AppendLine("</header>");
        sb.AppendLine("<main>");

        foreach (var htmlFile in htmlFiles) {
            AppendCard(sb, htmlFile);
        }

        sb.AppendLine("</main>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
        File.WriteAllText(Path.Combine(output, "index.html"), sb.ToString());
    }

    private static void AppendCard(System.Text.StringBuilder sb, string htmlFile) {
        var fileName = Path.GetFileName(htmlFile);
        var baseName = Path.GetFileNameWithoutExtension(htmlFile);
        var title = ReadTitle(htmlFile);
        sb.AppendLine("<article class=\"card\">");
        sb.AppendLine("<div class=\"preview\"><iframe loading=\"lazy\" src=\"" + EscapeHtml(fileName) + "\" title=\"" + EscapeHtml(title) + "\"></iframe></div>");
        sb.AppendLine("<div class=\"body\">");
        sb.AppendLine("<div class=\"title\">" + EscapeHtml(title) + "</div>");
        sb.AppendLine("<div class=\"links\">");
        sb.AppendLine("<a href=\"" + EscapeHtml(fileName) + "\">HTML</a>");
        sb.AppendLine("<a href=\"" + EscapeHtml(baseName) + ".svg\">SVG</a>");
        sb.AppendLine("<a href=\"" + EscapeHtml(baseName) + ".png\">PNG</a>");
        sb.AppendLine("</div>");
        sb.AppendLine("</div>");
        sb.AppendLine("</article>");
    }

    private static string ReadTitle(string htmlFile) {
        var html = File.ReadAllText(htmlFile);
        var start = html.IndexOf("<title>", StringComparison.OrdinalIgnoreCase);
        var end = html.IndexOf("</title>", StringComparison.OrdinalIgnoreCase);
        if (start < 0 || end <= start) return Path.GetFileNameWithoutExtension(htmlFile);
        return html.Substring(start + 7, end - start - 7).Trim();
    }

    private static string EscapeHtml(string value) => System.Net.WebUtility.HtmlEncode(value);
}
