using ChartForgeX.Primitives;
using ChartForgeX.Raster;
using ChartForgeX.Typography;
using Xunit;

namespace ChartForgeX.Tests;

/// <summary>
/// CFF (<c>.otf</c>) and CFF2 outlines: fonts generated by <see cref="OpenTypeTestFonts"/> are drawn
/// and their ink compared with the shapes their charstrings describe, then an installed CFF font,
/// when the host has one, is checked against its own advance widths.
/// </summary>
[Collection(nameof(FontRegistryCollection))]
public sealed class CompactFontOutlineTests : IDisposable {
    // At 100 px in a 1000-unit em one font unit is 0.1 px; the ascender (800) puts the baseline at y = 80.
    private const double Size = 100;
    private const double Baseline = 80;

    public void Dispose() => FontRegistry.Clear();

    [Fact]
    public void NameKeyedCffDrawsLinesCurvesSubroutinesAndHintedGlyphs() {
        var font = Load(OpenTypeTestFonts.NameKeyed());
        Assert.True(font.HasCompactOutlines);
        Assert.True(font.IsTextFace);

        // H: width, hstemhm/vstemhm, and a hint mask before a 100..500 x 0..700 rectangle.
        AssertInk(font, "H", 10, 50, Baseline - 70, Baseline);
        // O: four curves around a 193-unit radius; flattened chords stay inside the curve.
        AssertInk(font, "O", 10, 48.6, Baseline - 54.3, Baseline - 15.7);
        // x: a local and a global subroutine, 0..400 x 0..500.
        AssertInk(font, "x", 0, 40, Baseline - 50, Baseline);
        // A flex drawn as its two curves closes a 100..700 x 100..200 box.
        AssertInk(font, "F", 10, 70, Baseline - 20, Baseline - 10);
    }

    [Fact]
    public void SeacComposesTheBaseAndTheShiftedAccent() {
        var font = Load(OpenTypeTestFonts.NameKeyed());
        // e is a 50..450 x 0..400 box; the acute (200..350 x 500..650) is moved 50 units right.
        AssertInk(font, "é", 5, 45, Baseline - 65, Baseline);
        var accentOnly = Ink(font, "é", row => row < Baseline - 45);
        Assert.InRange(accentOnly.Left, 24, 26);
        Assert.InRange(accentOnly.Right, 39, 41);
    }

    [Fact]
    public void CidKeyedCffUsesTheLocalSubroutinesOfEachGlyphsFontDict() {
        var font = Load(OpenTypeTestFonts.CidKeyed());
        // x (font DICT 0) calls the first set's subroutine 0 as before.
        AssertInk(font, "x", 0, 40, Baseline - 50, Baseline);
        // e (font DICT 1) calls the same subroutine number, which there draws a 600..700 x 0..100 box.
        AssertInk(font, "e", 60, 70, Baseline - 10, Baseline);
    }

    [Fact]
    public void Cff2DrawsTheDefaultOfBlendedValuesWithoutEndchar() {
        var font = Load(OpenTypeTestFonts.Cff2());
        Assert.True(font.HasCompactOutlines);
        AssertInk(font, "H", 10, 50, Baseline - 70, Baseline);
    }

    [Fact]
    public void CffAdvancesComeFromHorizontalMetrics() {
        var font = Load(OpenTypeTestFonts.NameKeyed());
        Assert.Equal((600 + 500 + 600) / 10.0, font.Measure("HxH", Size), 6);
        Assert.Equal(80, font.Measure("F", Size), 6);
    }

    [Fact]
    public void DamagedCffTablesNeitherThrowNorDraw() {
        var bytes = OpenTypeTestFonts.NameKeyed();
        var random = new Random(1234);
        for (var attempt = 0; attempt < 200; attempt++) {
            var damaged = (byte[])bytes.Clone();
            for (var i = 0; i < 12; i++) damaged[random.Next(200, damaged.Length)] = (byte)random.Next(256);
            var font = TrueTypeFont.TryLoad(damaged);
            if (font == null) continue;
            var canvas = new RgbaCanvas(200, 120, 1, font, 1, useDefaultOutlineFont: false);
            font.Draw(canvas, 0, 0, "HOxeéF", ChartColor.Black, Size);
            font.Measure("HOxeéF", Size);
        }

        Assert.Null(TrueTypeFont.TryLoad(bytes.Take(bytes.Length / 2).ToArray()));
    }

    [Fact]
    public void OtfFilesAreIndexedAndRegistered() {
        var folder = Path.Combine(Path.GetTempPath(), "cfx-otf-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(folder);
        try {
            var path = Path.Combine(folder, "compact.otf");
            File.WriteAllBytes(path, OpenTypeTestFonts.NameKeyed());
            var faces = new List<InstalledFontFace>();
            InstalledFontCatalog.ReadFaces(path, faces);
            Assert.Equal(OpenTypeTestFonts.FamilyName, Assert.Single(faces).Family);
            Assert.True(InstalledFontCatalog.Index(new[] { folder }).ContainsKey(OpenTypeTestFonts.FamilyName));

            Assert.Equal(1, FontRegistry.RegisterFile(path));
            var face = TypographyFontResolver.ResolveFace(OpenTypeTestFonts.FamilyName + ", sans-serif", 400, false);
            Assert.Equal(path, face.Path);
            Assert.True(face.Font!.HasCompactOutlines);
            var measured = TextLayoutEngine.Measure("HxH", new TextStyle { Font = FontSpec.FromFamily(OpenTypeTestFonts.FamilyName), FontSize = Size });
            Assert.Equal(170, measured.Width, 6);
        } finally {
            FontRegistry.Clear();
            Directory.Delete(folder, true);
        }
    }

    [Fact]
    public void InstalledCffFontsInkWithinTheirAdvances() {
        var checkedFaces = 0;
        foreach (var directory in InstalledFontCatalog.FontDirectories()) {
            if (!Directory.Exists(directory)) continue;
            foreach (var file in Directory.EnumerateFiles(directory, "*.otf", SearchOption.AllDirectories).OrderBy(path => path, StringComparer.Ordinal).Take(6)) {
                var font = TrueTypeFont.TryLoadFromPath(file);
                if (font == null || !font.HasCompactOutlines || !font.IsTextFace) continue;
                const string text = "Hamburg 0123";
                var width = font.Measure(text, 40);
                var ink = Ink(font, text, _ => true, 40);
                Assert.True(ink.Right > ink.Left, "An installed CFF font should draw ink: " + file);
                Assert.InRange(ink.Left, -4, width * 0.2);
                Assert.InRange(ink.Right, width * 0.8, width + 4);
                checkedFaces++;
            }
        }

        // Hosts without an installed .otf (a default Windows install) have nothing to compare; the generated fonts above cover the reader.
        Assert.True(checkedFaces >= 0);
    }

    private static TrueTypeFont Load(byte[] data) {
        var font = TrueTypeFont.TryLoad(data);
        Assert.NotNull(font);
        return font!;
    }

    private static void AssertInk(TrueTypeFont font, string text, double left, double right, double top, double bottom) {
        var ink = Ink(font, text, _ => true);
        Assert.InRange(ink.Left, left - 1, left + 1);
        Assert.InRange(ink.Right, right - 1, right + 1);
        Assert.InRange(ink.Top, top - 1, top + 1);
        Assert.InRange(ink.Bottom, bottom - 1, bottom + 1);
    }

    private static (double Left, double Right, double Top, double Bottom) Ink(TrueTypeFont font, string text, Func<int, bool> rows, double size = Size) {
        var canvas = new RgbaCanvas(400, 160, 1, font, 1, useDefaultOutlineFont: false);
        font.Draw(canvas, 0, 0, text, ChartColor.Black, size);
        var pixels = canvas.ToOutputPixels();
        double left = double.MaxValue, right = double.MinValue, top = double.MaxValue, bottom = double.MinValue;
        for (var y = 0; y < canvas.OutputHeight; y++) {
            if (!rows(y)) continue;
            for (var x = 0; x < canvas.OutputWidth; x++) {
                if (pixels[(y * canvas.OutputWidth + x) * 4 + 3] < 128) continue;
                left = Math.Min(left, x);
                right = Math.Max(right, x + 1);
                top = Math.Min(top, y);
                bottom = Math.Max(bottom, y + 1);
            }
        }

        return (left, right, top, bottom);
    }
}
